version: '3.8'
services:
  postgres:
    image: postgres:15       # Versión estable de Postgres
    container_name: rpg-db
    environment:
      POSTGRES_USER: rpg_user
      POSTGRES_PASSWORD: superpass
      POSTGRES_DB: rpg_database
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
